title: "Elixir ծրագրավորման լեզու"
description: "Elixir ծրագրավորման լեզվի մասին հոդվածներ, ուսումնական նյութեր և նորություններ"
lang: hy

url: "https://vontanne.github.io"
baseurl: "/elixir-hy"

theme: jekyll-theme-cayman

collections:
  publications:
    output: true
    permalink: /publications/:name.html

plugins:
  - jekyll-seo-tag
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

readme_index:
  with_frontmatter: true

webmaster_verifications:
  google: "-_d57q3Ay8v6w2XtvhHcix1tv-LrtFEqu-xV5j9VAd8"
  bing: "A1D2424884B0A9F9C5C41DF385FFC491"
